/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Clases.Clientes;
import Clases.DaoClientes;

/**
 *
 * @author ntnrc
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
        setResizable(false);
        setTitle("Agregar");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonGestion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonReporte = new javax.swing.JButton();
        jLabelinfo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelNomC = new javax.swing.JLabel();
        jTextFieldNomC = new javax.swing.JTextField();
        jLabelDirC = new javax.swing.JLabel();
        jTextFieldDirC = new javax.swing.JTextField();
        jLabelDirA = new javax.swing.JLabel();
        jLabelNomA = new javax.swing.JLabel();
        jTextFieldNomA = new javax.swing.JTextField();
        jTextFieldDirA = new javax.swing.JTextField();
        jLabelGar = new javax.swing.JLabel();
        jTextFieldGar = new javax.swing.JTextField();
        jLabelPrestamo = new javax.swing.JLabel();
        jTextFieldPrestamo = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 52, 133));
        jPanel2.setPreferredSize(new java.awt.Dimension(225, 490));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonGestion.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jButtonGestion.setText("Gestión");
        jButtonGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 65, 125, 50));

        jPanel3.setBackground(new java.awt.Color(108, 60, 137));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 130));

        jButtonReporte.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jButtonReporte.setText("Reporte");
        jButtonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 161, 125, 50));

        jLabelinfo.setFont(new java.awt.Font("Caladea", 3, 24)); // NOI18N
        jLabelinfo.setText("i");
        jLabelinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelinfoMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 17, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 530));

        jPanel1.setBackground(new java.awt.Color(108, 60, 137));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 130));

        jPanel4.setBackground(new java.awt.Color(238, 243, 224));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Micro Préstamos");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jPanel5.setBackground(new java.awt.Color(108, 60, 137));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomC.setText("Nombre Cliente:");
        jPanel5.add(jLabelNomC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jTextFieldNomC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomCActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldNomC, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 48, 240, -1));

        jLabelDirC.setText("Direccion Cliente: ");
        jPanel5.add(jLabelDirC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 81, -1, -1));
        jPanel5.add(jTextFieldDirC, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 79, 240, -1));

        jLabelDirA.setText("Dirección Aval:");
        jPanel5.add(jLabelDirA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 141, -1, -1));

        jLabelNomA.setText("Nombre Aval:");
        jPanel5.add(jLabelNomA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));
        jPanel5.add(jTextFieldNomA, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 110, 240, -1));
        jPanel5.add(jTextFieldDirA, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 141, 240, -1));

        jLabelGar.setText("Garantias:");
        jPanel5.add(jLabelGar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 172, -1, -1));
        jPanel5.add(jTextFieldGar, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 172, 240, -1));

        jLabelPrestamo.setText("Prestamo: ");
        jPanel5.add(jLabelPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 201, -1, -1));
        jPanel5.add(jTextFieldPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 199, 240, -1));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 380, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 660, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionActionPerformed
        Gestion gestion= new Gestion();
        gestion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGestionActionPerformed

    private void jButtonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteActionPerformed
        Reporte reporte= new Reporte();
        reporte.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonReporteActionPerformed

    private void jLabelinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelinfoMouseClicked
        Informacion informacion= new Informacion();
        informacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelinfoMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextFieldNomCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomCActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String nomC = jTextFieldNomC.getText();
        String dir = jTextFieldDirC.getText();
        String nomA = jTextFieldNomA.getText();
        String dirA = jTextFieldDirA.getText();
        String gar = jTextFieldGar.getText();
        
        String x=jTextFieldPrestamo.getText();
        double prestamo=Double.parseDouble(x);
        double pays = prestamo/10;
        int semanas = 0;
        Clientes cliente = new Clientes(semanas, nomC, dir, nomA, dirA, gar, pays, prestamo);
        
        try{
            DaoClientes.insertar(cliente);
        } catch (SQLException ex){
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            jTextFieldDirA.setText("");
            jTextFieldDirC.setText("");
            jTextFieldGar.setText("");
            jTextFieldNomA.setText("");
            jTextFieldNomC.setText("");
            jTextFieldPrestamo.setText("");
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonGestion;
    private javax.swing.JButton jButtonReporte;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDirA;
    private javax.swing.JLabel jLabelDirC;
    private javax.swing.JLabel jLabelGar;
    private javax.swing.JLabel jLabelNomA;
    private javax.swing.JLabel jLabelNomC;
    private javax.swing.JLabel jLabelPrestamo;
    private javax.swing.JLabel jLabelinfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextFieldDirA;
    private javax.swing.JTextField jTextFieldDirC;
    private javax.swing.JTextField jTextFieldGar;
    private javax.swing.JTextField jTextFieldNomA;
    private javax.swing.JTextField jTextFieldNomC;
    private javax.swing.JTextField jTextFieldPrestamo;
    // End of variables declaration//GEN-END:variables
}